# CircleCI configuration file
# https://circleci.com/docs/2.0/language-android
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/kotlin-sample-app
    docker:
      - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run: echo "marvel_public_key=$MARVEL_PUBLIC_KEY" >> local.properties
      - run: echo "marvel_private_key=$MARVEL_PRIVATE_KEY" >> local.properties
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
      - run:
          name: Run Lint
          command: ./gradlew lintDebug
      - run:
          name: Run Spotless
          command: ./gradlew spotlessKotlinCheck
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - run:
          name: Generate Code Coverage
          command: ./gradlew jacocoTestReport
      - codecov/upload:
          flags: unittest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
